spring:
  application:
    name: blindaje-digital

  datasource:
    url: jdbc:postgresql://localhost:5432/blindaje
    username: blindaje
    password: blindaje
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080